#!/usr/bin/env bash

echo "Creating the database user: ${PROBEDOCK_DATABASE_USERNAME}"
psql -U "$POSTGRES_USER" -c "CREATE USER ${PROBEDOCK_DATABASE_USERNAME} PASSWORD '${PROBEDOCK_DATABASE_PASSWORD}'"

echo "Creating the database: ${PROBEDOCK_DATABASE_USERNAME}"
createdb -U "$POSTGRES_USER" -O $PROBEDOCK_DATABASE_USERNAME $PROBEDOCK_DATABASE_NAME