FROM ruby:2.2

# Install curl and postgresql.
RUN apt-get update \
    && apt-get install -q -y curl postgresql-client

# Install Node.js.
RUN curl -sSLo /tmp/node.tar.xz https://nodejs.org/dist/v4.4.4/node-v4.4.4-linux-x64.tar.xz \
    && tar -C /usr/local --strip-components 1 -xf /tmp/node.tar.xz \
    && rm -f /tmp/node.tar.xz

# Install s6 (for service supervision: https://github.com/just-containers/s6-overlay).
RUN curl -sSLo /tmp/s6.tar.gz https://github.com/just-containers/s6-overlay/releases/download/v1.17.2.0/s6-overlay-amd64.tar.gz \
    && tar xzf /tmp/s6.tar.gz -C / \
    && rm -f /tmp/s6.tar.gz

# Install serf.
RUN mkdir /opt/bin \
    && echo "export PATH=/opt/bin:$PATH" >> /root/.bashrc \
    && curl -sSLo /tmp/serf.gz https://releases.hashicorp.com/serf/0.7.0/serf_0.7.0_linux_amd64.zip \
    && gunzip -c /tmp/serf.gz > /opt/bin/serf \
    && chmod 755 /opt/bin/serf \
    && rm -f /tmp/serf.gz

# Install gems.
RUN mkdir -p /usr/src/app
WORKDIR /usr/src/app

COPY probedock/Gemfile /usr/src/app/Gemfile
COPY probedock/Gemfile.lock /usr/src/app/Gemfile.lock

RUN bundle install --without development test

# Clean up.
RUN apt-get clean \
    && rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*

# Set s6 as the entrypoint.
ENTRYPOINT ["/init"]

# throw errors if Gemfile has been modified since Gemfile.lock
RUN bundle config --global frozen 1
