FROM probedock/probedock-common

COPY config/cont-finish.d /etc/cont-finish.d
COPY config/cont-init.d /etc/cont-init.d
COPY config/services.d /etc/services.d
COPY config/serf.conf /etc/serf.conf

EXPOSE 3000
